ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.aethink.SerializationKt.configureSerialization
      - com.aethink.SecurityKt.configureSecurity
      - com.aethink.StatusPagesKt.configureStatusPages
      - com.aethink.ResourcesKt.configureResources
      - com.aethink.RoutingKt.configureRouting
