ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.aethink.plugin.SerializationKt.configureSerialization
      - com.aethink.plugin.SecurityKt.configureSecurity
      - com.aethink.plugin.StatusPagesKt.configureStatusPages
      - com.aethink.plugin.RoutingKt.configureRouting
